name = "CQDBasics"
uuid = "12249ded-1a98-4eef-b7b6-1f94d482381c"
authors = ["Xukun Lin"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
